version: '1.0'

services:
  frontend:
    container_name: nuxt_portfolio
    hostname: nuxt.portfolio
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8100:8100"
    networks:
      - portfolio_network

networks:
  portfolio_network:
    driver: bridge